#:schema https://gitdot.io/schema/gitdot-ci.json

[[builds]]
trigger = "push_to_main"
tasks = ["build", "build2"]

[[tasks]]
name = "build"
command = "cargo clean && just build"

[[tasks]]
name = "build2"
command = "cargo clean && just build"
